name: Publish

on:
  push:
  workflow_dispatch:
  schedule:
    # Auto-Update on Fridays
    - cron: 0 1 * * FRI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install ts
        run: sudo apt install moreutils

      - name: Install opam & packages
        run: bash ./setup_dev.sh
